BlogSite/config/routes.rb
Rails.application.routes.draw do

  get 'cocs/show'

  get 'cocs/new'

  get 'cocs/browse'

  get 'comments/show'

  get 'comments/new'

  get 'comments/browse'

  resources :image do
    get "serve", :on => :member
  end

  root :to => 'posts#index'

  get '/home' => 'home#home'

  get 'comment/create'

  get 'comment/delete'

  get 'comment/index'

  get 'comment/edit'

  get '/members/show'

  get '/members/add'

  get '/members/block'

  get '/members/unblock'

  get '/members/create'

  get '/members/login'

  get '/members/:id'=> 'members#show'

  get '/members/edit/:id' => 'members#edit'

  post 'members/delete/:id' => 'members#delete'

  post 'members/block/:id' => 'members#block'

  post '/members/create' => 'members#signup'

  post '/members/edit/:id' => 'members#update'

  post '/members/add' => 'members#authorize'

  post '/members/block' => 'members#blockuser'

  post '/members/unblock' => 'members#unblockuser'
  
  post 'members/deleteImage' => 'members#deleteImage'

  get '/posts/new'

  post 'posts/new' => 'posts#create'

  get '/posts/:id' => 'posts#show'

  get '/posts/delete'

  get '/posts/index'

  get 'posts/edit/:id' => 'posts#edit'
  get '/tags/index' => 'tags#index'
  resources :tags
  
  resources :posts
  get '/comments/new'
get '/comments/browse'
get '/comments/:id' => 'comments#show'
get 'cocs/new'
   get'/cocs/browse'
   get 'cocs/:id' => 'cocs#show'
   
   post 'cocs/new' => 'cocs#create'
post '/comments/new' => 'comments#create'

  post 'posts/edit/:id' => 'posts#update'

  delete 'posts/:id' => 'posts#delete'

  post 'signout' => 'login#logout'

  post 'login' => 'login#login'

  get 'login' => 'login#new'

end

BlogSite/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
  def to_s
    name
  end
end

BlogSite/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  @tag = Tag.find(params[:id])
end

def index
  @tags = Tag.all.order('created_at DESC')
end
end

BlogSite/app/helpers/tags_helper.rb
module TagsHelper
end

BlogSite/app/views/tags/index.html.erb
<div id="page_wrapper">
	<b>INDEX</b>
	<% @tags.each do |tag| %>
	<div class="tag_wrapper">

		<tr>
			<td><h2 class="title"> <%= link_to tag.name.capitalize, tag_path(tag) %> </h2></td>
			<div style="text-align: right">
				<br>
				<br>
			</div>
			<p class="date">
				<%= tag.created_at.strftime("%d %B %Y")%>
			</p>

		</tr>
	</div>
	<% end %>
</div>

BlogSite/app/views/tags/show.html.erb
<h1>Posts Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>